export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    OTP_VALIDATION_REQUEST: 'OTP_VALIDATION_REQUEST',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',
    LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',


    UPDATE_EMPLOYEE_REQUEST: 'UPDATE_EMPLOYEE_REQUEST',
    UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
    UPDATE_EMPLOYEE_FAILURE: 'UPDATE_EMPLOYEE_FAILURE',

    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS',
    ADD_EMPLOYEE_FAILURE: 'ADD_EMPLOYEE_FAILURE',

    HISTORY_REQUEST: 'HISTORY_REQUEST',
    HISTORY_SUCCESS: 'HISTORY_SUCCESS',
    HISTORY_FAILURE: 'HISTORY_FAILURE',
    HISTORY_CLEAR: 'HISTORY_CLEAR',


    SUB_SWITCH_REQUEST: 'SUB_SWITCH_REQUEST',
    SUB_SWITCH_SUCCESS: 'SUB_SWITCH_SUCCESS',
    SUB_SWITCH_FAILURE: 'SUB_SWITCH_FAILURE'


};